### ISSUE TITLE
Make openhands-solver workflow referencable

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/openhands-resolver#133]
I am attempting to call openhands-resolver.yml from an external repo using the following code:

```yaml
name: Resolve Issues with OpenHands Resolver

on:
  issues:
    types: [labeled]

jobs:
  call-openhands-resolver:
    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@main
    if: github.event.label.name == 'fix-me'
    secrets: inherit
```

However, when I do this, I get the following error: "workflow_call key is not defined in the referenced workflow"
